image: node:latest

stages:
  - test
  - release

test:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run test

release:
  stage: release
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
  only:
    - master
    - tags